module.exports = [
"[project]/.next-internal/server/app/media-preview/[filter]/page/actions.js [app-rsc] (server actions loader, ecmascript)", ((__turbopack_context__, module, exports) => {

}),
"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/components/shader-studio.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "MediaThumbnail",
    ()=>MediaThumbnail,
    "ShaderStudio",
    ()=>ShaderStudio,
    "StaticMediaPreview",
    ()=>StaticMediaPreview,
    "StaticStylePreview",
    ()=>StaticStylePreview,
    "resolveMediaPreviewFilter",
    ()=>resolveMediaPreviewFilter
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const MediaThumbnail = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call MediaThumbnail() from the server but MediaThumbnail is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx <module evaluation>", "MediaThumbnail");
const ShaderStudio = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ShaderStudio() from the server but ShaderStudio is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx <module evaluation>", "ShaderStudio");
const StaticMediaPreview = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call StaticMediaPreview() from the server but StaticMediaPreview is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx <module evaluation>", "StaticMediaPreview");
const StaticStylePreview = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call StaticStylePreview() from the server but StaticStylePreview is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx <module evaluation>", "StaticStylePreview");
const resolveMediaPreviewFilter = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call resolveMediaPreviewFilter() from the server but resolveMediaPreviewFilter is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx <module evaluation>", "resolveMediaPreviewFilter");
}),
"[project]/components/shader-studio.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "MediaThumbnail",
    ()=>MediaThumbnail,
    "ShaderStudio",
    ()=>ShaderStudio,
    "StaticMediaPreview",
    ()=>StaticMediaPreview,
    "StaticStylePreview",
    ()=>StaticStylePreview,
    "resolveMediaPreviewFilter",
    ()=>resolveMediaPreviewFilter
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const MediaThumbnail = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call MediaThumbnail() from the server but MediaThumbnail is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx", "MediaThumbnail");
const ShaderStudio = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ShaderStudio() from the server but ShaderStudio is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx", "ShaderStudio");
const StaticMediaPreview = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call StaticMediaPreview() from the server but StaticMediaPreview is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx", "StaticMediaPreview");
const StaticStylePreview = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call StaticStylePreview() from the server but StaticStylePreview is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx", "StaticStylePreview");
const resolveMediaPreviewFilter = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call resolveMediaPreviewFilter() from the server but resolveMediaPreviewFilter is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/shader-studio.tsx", "resolveMediaPreviewFilter");
}),
"[project]/components/shader-studio.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/shader-studio.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/shader-studio.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/components/shader-studio/samples.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "defaultMediaSource",
    ()=>defaultMediaSource,
    "defaultSampleId",
    ()=>defaultSampleId,
    "getSampleById",
    ()=>getSampleById,
    "pickRandomSample",
    ()=>pickRandomSample,
    "resolveMediaSource",
    ()=>resolveMediaSource,
    "sampleAssets",
    ()=>sampleAssets,
    "samplesForKind",
    ()=>samplesForKind
]);
const sampleAssets = [
    {
        id: "aurora",
        path: "/samples/aurora.png",
        type: "image",
        tags: [
            "abstract",
            "texture"
        ],
        for: [
            "media",
            "ascii"
        ],
        label: "Aurora"
    },
    {
        id: "caustics",
        path: "/samples/caustics.png",
        type: "image",
        tags: [
            "texture",
            "abstract"
        ],
        for: [
            "media",
            "ascii"
        ],
        label: "Caustics"
    },
    {
        id: "portrait-a",
        path: "/samples/556397c6096c0af0913bbc28bdb3de60.jpg",
        type: "image",
        tags: [
            "portrait"
        ],
        for: [
            "media",
            "ascii"
        ],
        label: "Portrait A"
    },
    {
        id: "portrait-b",
        path: "/samples/5e849d31302c296faeaee27449900509.jpg",
        type: "image",
        tags: [
            "portrait"
        ],
        for: [
            "media",
            "ascii"
        ],
        label: "Portrait B"
    },
    {
        id: "generated-1",
        path: "/samples/Generated%20image%201.png",
        type: "image",
        tags: [
            "abstract",
            "product"
        ],
        for: [
            "media",
            "ascii"
        ],
        label: "Generated 1"
    },
    {
        id: "generated-2",
        path: "/samples/generated-image-1783984312949.png",
        type: "image",
        tags: [
            "abstract",
            "texture"
        ],
        for: [
            "media",
            "ascii"
        ],
        label: "Generated 2"
    },
    {
        id: "thermal-loop",
        path: "/shaders/thermal-loop.webm",
        type: "video",
        tags: [
            "loop",
            "abstract"
        ],
        for: [
            "media",
            "ascii"
        ],
        label: "Thermal loop"
    }
];
function samplesForKind(kind = "media") {
    return sampleAssets.filter((asset)=>asset.for.includes(kind));
}
function getSampleById(id) {
    return sampleAssets.find((asset)=>asset.id === id) ?? null;
}
function defaultSampleId(kind = "media") {
    return samplesForKind(kind)[0]?.id ?? sampleAssets[0]?.id ?? "aurora";
}
function defaultMediaSource(kind = "media") {
    return {
        type: "sample",
        sampleId: defaultSampleId(kind)
    };
}
function resolveMediaSource(source) {
    if (!source) return null;
    if (source.type === "upload") {
        return {
            url: source.dataUrl,
            mediaType: source.mime
        };
    }
    const sample = getSampleById(source.sampleId);
    if (!sample) return null;
    return {
        url: sample.path,
        mediaType: sample.type,
        sampleId: sample.id
    };
}
function pickRandomSample(kind = "media", exceptId) {
    const pool = samplesForKind(kind).filter((asset)=>asset.id !== exceptId);
    const list = pool.length ? pool : samplesForKind(kind);
    if (!list.length) return defaultMediaSource(kind);
    return {
        type: "sample",
        sampleId: list[Math.floor(Math.random() * list.length)].id
    };
}
}),
"[project]/components/shader-studio/media-catalog.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getMediaFilter",
    ()=>getMediaFilter,
    "isMediaFilterId",
    ()=>isMediaFilterId,
    "isPaperMediaFilter",
    ()=>isPaperMediaFilter,
    "isVfxMediaFilter",
    ()=>isVfxMediaFilter,
    "mediaFilterGroups",
    ()=>mediaFilterGroups,
    "mediaFilterIds",
    ()=>mediaFilterIds,
    "mediaFilterNames",
    ()=>mediaFilterNames,
    "mediaFilters",
    ()=>mediaFilters,
    "mediaPaperProps",
    ()=>mediaPaperProps,
    "mediaPreviewSampleId",
    ()=>mediaPreviewSampleId,
    "mediaPreviewSampleIds",
    ()=>mediaPreviewSampleIds,
    "pickOtherMediaFilter",
    ()=>pickOtherMediaFilter,
    "resolveMediaPreviewFilter",
    ()=>resolveMediaPreviewFilter
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2f$samples$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/shader-studio/samples.ts [app-rsc] (ecmascript)");
;
const mediaFilters = [
    {
        id: "paper-water",
        engine: "paper",
        label: "Water",
        group: "Paper"
    },
    {
        id: "paper-fluted-glass",
        engine: "paper",
        label: "Fluted glass",
        group: "Paper"
    },
    {
        id: "paper-texture",
        engine: "paper",
        label: "Paper texture",
        group: "Paper"
    },
    {
        id: "paper-image-dithering",
        engine: "paper",
        label: "Image dither",
        group: "Paper"
    },
    {
        id: "paper-halftone-dots",
        engine: "paper",
        label: "Halftone dots",
        group: "Paper"
    },
    {
        id: "paper-halftone-cmyk",
        engine: "paper",
        label: "Halftone CMYK",
        group: "Paper"
    },
    {
        id: "paper-liquid-metal",
        engine: "paper",
        label: "Liquid metal",
        group: "Paper"
    },
    {
        id: "paper-heatmap",
        engine: "paper",
        label: "Heatmap",
        group: "Paper"
    },
    {
        id: "paper-gem-smoke",
        engine: "paper",
        label: "Gem smoke",
        group: "Paper"
    },
    {
        id: "vfx-glitch",
        engine: "vfx",
        label: "Glitch",
        group: "Digital"
    },
    {
        id: "vfx-chromatic",
        engine: "vfx",
        label: "Chromatic",
        group: "Digital"
    },
    {
        id: "vfx-rgb-shift",
        engine: "vfx",
        label: "RGB shift",
        group: "Digital"
    },
    {
        id: "vfx-scanline",
        engine: "vfx",
        label: "Scanline",
        group: "Digital"
    },
    {
        id: "vfx-pixelate",
        engine: "vfx",
        label: "Pixelate",
        group: "Digital"
    },
    {
        id: "vfx-bloom",
        engine: "vfx",
        label: "Bloom",
        group: "Digital"
    },
    {
        id: "vfx-fluid",
        engine: "vfx",
        label: "Fluid",
        group: "Digital"
    }
];
const mediaFilterIds = mediaFilters.map((filter)=>filter.id);
const mediaFilterGroups = [
    {
        title: "Paper",
        items: mediaFilters.filter((filter)=>filter.group === "Paper")
    },
    {
        title: "Digital",
        items: mediaFilters.filter((filter)=>filter.group === "Digital")
    }
];
const mediaFilterNames = Object.fromEntries(mediaFilters.map((filter)=>[
        filter.id,
        filter.label
    ]));
function isMediaFilterId(value) {
    return typeof value === "string" && mediaFilterIds.includes(value);
}
function getMediaFilter(id) {
    return mediaFilters.find((filter)=>filter.id === id) ?? mediaFilters[0];
}
function pickOtherMediaFilter(current) {
    const choices = mediaFilterIds.filter((id)=>id !== current);
    return choices[Math.floor(Math.random() * choices.length)] ?? current;
}
const mediaPreviewSampleIds = {
    "paper-water": "caustics",
    "paper-fluted-glass": "portrait-a",
    "paper-texture": "aurora",
    "paper-image-dithering": "portrait-b",
    "paper-halftone-dots": "generated-1",
    "paper-halftone-cmyk": "portrait-a",
    "paper-liquid-metal": "portrait-a",
    "paper-heatmap": "portrait-b",
    "paper-gem-smoke": "aurora",
    "vfx-glitch": "portrait-b",
    "vfx-chromatic": "portrait-b",
    "vfx-rgb-shift": "generated-1",
    "vfx-scanline": "caustics",
    "vfx-pixelate": "portrait-a",
    "vfx-bloom": "portrait-a",
    "vfx-fluid": "caustics"
};
function mediaPreviewSampleId(filterId) {
    return mediaPreviewSampleIds[filterId] ?? (0, __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2f$samples$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["defaultSampleId"])("media");
}
function resolveMediaPreviewFilter(value) {
    return isMediaFilterId(value) ? value : "paper-water";
}
function isPaperMediaFilter(id) {
    return getMediaFilter(id).engine === "paper";
}
function isVfxMediaFilter(id) {
    return getMediaFilter(id).engine === "vfx";
}
function mediaPaperProps(recipe, frozen, image) {
    const palette = recipe.palette;
    const speed = frozen || !recipe.animate ? 0 : (recipe.reverse ? -1 : 1) * (0.15 + recipe.speed * 0.55);
    const shared = {
        image,
        speed,
        scale: Math.max(0.2, Math.min(3.5, recipe.zoom)),
        rotation: recipe.rotate * 180 / Math.PI,
        offsetX: recipe.offsetX,
        offsetY: recipe.offsetY,
        fit: "cover",
        frame: recipe.seed
    };
    switch(recipe.mediaFilter){
        case "paper-water":
            return {
                ...shared,
                colorBack: palette[0],
                colorHighlight: palette.at(-1) ?? "#ffffff",
                highlights: recipe.intensity,
                caustic: 0.25 + recipe.warp * 0.75,
                waves: recipe.warp,
                edges: recipe.contrast,
                layering: recipe.drift,
                size: 0.4 + recipe.zoom
            };
        case "paper-fluted-glass":
            return {
                ...shared,
                colorBack: palette[0],
                colorShadow: palette[1] ?? "#000000",
                colorHighlight: palette.at(-1) ?? "#ffffff",
                distortion: recipe.warp,
                shape: "wave",
                angle: (recipe.rotate * 180 / Math.PI + 360) % 180,
                size: 0.2 + recipe.intensity * 0.6,
                shadows: recipe.contrast,
                highlights: recipe.intensity * 0.5,
                stretch: recipe.drift,
                blur: Math.min(1, recipe.blur / 20),
                edges: recipe.contrast,
                grainMixer: recipe.grain * 4,
                grainOverlay: recipe.grain * 2
            };
        case "paper-texture":
            return {
                ...shared,
                colorFront: palette.at(-1) ?? "#ffffff",
                colorBack: palette[0],
                contrast: recipe.contrast,
                roughness: recipe.grain * 8,
                fiber: recipe.intensity,
                crumples: recipe.warp,
                folds: recipe.drift,
                drops: recipe.grain * 4,
                seed: recipe.seed,
                fade: Math.min(1, recipe.blur / 20)
            };
        case "paper-image-dithering":
            return {
                ...shared,
                colorBack: palette[0],
                colorFront: palette.at(-1) ?? "#ffffff",
                colorHighlight: palette[1] ?? palette.at(-1) ?? "#ffffff",
                type: recipe.smoothBlend ? "random" : "4x4",
                size: 1 + recipe.warp * 4,
                colorSteps: Math.max(2, Math.round(2 + recipe.intensity * 6)),
                inverted: recipe.reverse
            };
        case "paper-halftone-dots":
            return {
                ...shared,
                colorBack: palette[0],
                colorFront: palette.at(-1) ?? "#ffffff",
                type: "dots",
                grid: 8 + recipe.warp * 24,
                size: 0.4 + recipe.intensity * 0.8
            };
        case "paper-halftone-cmyk":
            return {
                ...shared,
                type: "cmyk",
                grid: 6 + recipe.warp * 20,
                size: 0.35 + recipe.intensity * 0.7
            };
        case "paper-liquid-metal":
            return {
                ...shared,
                colorBack: palette[0],
                colorTint: palette[1] ?? palette.at(-1) ?? "#c0c0c0",
                repetition: 1 + recipe.warp * 4,
                softness: 1 - recipe.contrast,
                shiftRed: recipe.drift * 0.4,
                shiftBlue: recipe.intensity * 0.4,
                distortion: recipe.warp,
                contour: recipe.contrast,
                angle: recipe.rotate * 40,
                liquidity: recipe.intensity
            };
        case "paper-heatmap":
            return {
                ...shared,
                colors: palette.slice(0, 5),
                soft: recipe.smoothBlend ? 1 : 0.3,
                intensity: recipe.intensity
            };
        case "paper-gem-smoke":
            return {
                ...shared,
                colorBack: palette[0],
                colorTint: palette[1] ?? "#88aaff",
                colorFresh: palette.at(-1) ?? "#ffffff",
                soft: recipe.smoothBlend ? 1 : 0.35,
                intensity: recipe.intensity,
                smoke: recipe.grain * 4 + recipe.warp
            };
        default:
            return shared;
    }
}
}),
"[project]/app/media-preview/[filter]/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>MediaPreviewPage
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/shader-studio.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2f$media$2d$catalog$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/shader-studio/media-catalog.ts [app-rsc] (ecmascript)");
;
;
;
async function MediaPreviewPage({ params }) {
    const { filter } = await params;
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["StaticMediaPreview"], {
        filter: (0, __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$shader$2d$studio$2f$media$2d$catalog$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["resolveMediaPreviewFilter"])(filter)
    }, void 0, false, {
        fileName: "[project]/app/media-preview/[filter]/page.tsx",
        lineNumber: 6,
        columnNumber: 10
    }, this);
}
}),
"[project]/app/media-preview/[filter]/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/media-preview/[filter]/page.tsx [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__2df7ca89._.js.map